import type { FeedPost } from "@/types/database";

export const MOCK_FEED: FeedPost[] = [
  {
    id: "1",
    author_id: "u1",
    type: "code_template",
    title: "Neon Arcane Profile Theme",
    description: "A glowing fantasy profile layout with rune borders and inventory tabs.",
    content: null,
    html_code: "<div class='rpg-card'><h1>Lyra Moonwhisper</h1><p>Level 42 · Arcane Weaver</p></div>",
    css_code: ".rpg-card { padding: 2rem; border: 2px solid #a78bfa; border-radius: 1rem; background: #1a1033; color: #e9d5ff; box-shadow: 0 0 24px #7c3aed44; }",
    js_code: null,
    bbcode: null,
    preview_image_url: null,
    pricing: "free",
    price_cents: 0,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["profile", "fantasy"],
    style_tags: ["dark", "mystical"],
    like_count: 128,
    comment_count: 14,
    created_at: new Date().toISOString(),
    author: {
      id: "u1",
      username: "lyra_weaver",
      display_name: "Lyra Moonwhisper",
      bio: "Building arcane UI for RPG personas.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "2",
    author_id: "u2",
    type: "character_sheet",
    title: "Kael — Cyber Ronin Sheet",
    description: "Full stat block + lore for a sci-fi samurai character.",
    content: "STR 14 · DEX 18 · Tech Affinity: Neural Blade",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: null,
    preview_image_url: null,
    pricing: "one_time",
    price_cents: 499,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["character", "sci-fi"],
    style_tags: ["cyberpunk", "anime"],
    like_count: 89,
    comment_count: 7,
    created_at: new Date().toISOString(),
    author: {
      id: "u2",
      username: "roninforge",
      display_name: "Ronin Forge",
      bio: null,
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: false,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "3",
    author_id: "u3",
    type: "story_segment",
    title: "Chapter III — The Hollow Gate",
    description: "Collaborative horror RPG thread, turn 12.",
    content: "The lantern flickered once, then twice — and the gate breathed.",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: "[b]GM:[/b] Roll for sanity.",
    preview_image_url: null,
    pricing: "free",
    price_cents: 0,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["horror", "collab"],
    style_tags: ["dark"],
    like_count: 203,
    comment_count: 41,
    created_at: new Date().toISOString(),
    author: {
      id: "u3",
      username: "hollowscribe",
      display_name: "Hollow Scribe",
      bio: "Co-writing nightmares since 2019.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
];
