import type { FeedPost, RpgForum } from "@/types/database";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const MOCK_FEED: FeedPost[] = [
  {
    id: "1",
    author_id: "u1",
    type: "code_template",
    title: "Neon Arcane Profile Theme",
    description: "A glowing fantasy profile layout with rune borders and inventory tabs.",
    plot_synopsis: null,
    content: null,
    html_code: "<div class='rpg-card'><h1>Chaz Copper</h1><p>Level 42 · Arcane Weaver</p></div>",
    css_code: ".rpg-card { padding: 2rem; border: 3px solid #e63946; border-radius: 4px; background: #1d3557; color: #f1faee; font-family: Georgia, serif; text-align: center; }",
    js_code: null,
    bbcode: null,
    preview_image_url:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=560&fit=crop",
    book_cover_url: null,
    invite_token: "invite-neon-arcane",
    pricing: "free",
    price_cents: 0,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["profile", "fantasy"],
    style_tags: ["retro", "fantasy"],
    like_count: 128,
    comment_count: 2,
    created_at: daysAgo(14),
    author: {
      id: "u1",
      username: "chaz_copper",
      display_name: "Chaz Copper",
      bio: "Building arcane UI for RPG personas.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "2",
    author_id: "u2",
    type: "character_sheet",
    title: "Kael — Cyber Ronin Sheet",
    description: "Full stat block + lore for a sci-fi samurai character.",
    plot_synopsis:
      "In the rain-soaked sprawl of Neo-Kyoto, a ronin with a neural blade hunts the syndicate that erased his clan. Stats, gear, and a past he cannot remember.",
    content: "STR 14 · DEX 18 · Tech Affinity: Neural Blade",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: null,
    preview_image_url: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=400&h=560&fit=crop",
    book_cover_url: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=400&h=560&fit=crop",
    invite_token: null,
    pricing: "one_time",
    price_cents: 499,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["character", "sci-fi"],
    style_tags: ["cyberpunk", "comics"],
    like_count: 89,
    comment_count: 0,
    created_at: daysAgo(12),
    author: {
      id: "u2",
      username: "roninforge",
      display_name: "Ronin Forge",
      bio: null,
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: false,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "3",
    author_id: "u3",
    type: "story_segment",
    title: "The Hollow Gate",
    description: "Collaborative horror RPG thread.",
    plot_synopsis:
      "When the lantern dies at the forest edge, seven travelers find a gate that breathes. A slow-burn horror tale of sanity, secrets, and what waits on the other side.",
    content: "The lantern flickered once, then twice — and the gate breathed.",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: "[b]GM:[/b] Roll for sanity.",
    preview_image_url: null,
    book_cover_url: "https://images.unsplash.com/photo-1448375240586-882707db889b?w=400&h=560&fit=crop",
    invite_token: null,
    pricing: "free",
    price_cents: 0,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["horror", "collab", "story"],
    style_tags: ["dark", "retro"],
    like_count: 203,
    comment_count: 2,
    created_at: daysAgo(9),
    author: {
      id: "u3",
      username: "leon_jezz",
      display_name: "Leon Jezz",
      bio: "Co-writing nightmares since 2019.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "4",
    author_id: "u1",
    type: "text_writing",
    title: "Letters from the Ashwood",
    description: "Epistolary fantasy — two mages write across a war.",
    plot_synopsis:
      "Two archivists separated by the Ashwood War exchange letters that slowly reveal a third voice in the margins. A quiet fantasy about memory, magic, and misdelivered truths.",
    content: "Dearest Maren,\n\nThe ink here smells of cedar and old vows...",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: null,
    preview_image_url: null,
    book_cover_url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=560&fit=crop",
    invite_token: null,
    pricing: "free",
    price_cents: 0,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["fantasy", "letters", "story"],
    style_tags: ["retro", "romance"],
    like_count: 56,
    comment_count: 1,
    created_at: daysAgo(7),
    author: {
      id: "u1",
      username: "chaz_copper",
      display_name: "Chaz Copper",
      bio: "Building arcane UI for RPG personas.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "5",
    author_id: "u2",
    type: "digital_asset",
    title: "Ronin Portrait Pack",
    description: "Three cyber-samurai avatar illustrations.",
    plot_synopsis: "3 illustrated portraits — teaser shown blurred until you sign in.",
    content: null,
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: null,
    preview_image_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=400&fit=crop",
    illustration_images: [
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1518709268805-4e9042af9b33?w=800&h=800&fit=crop",
    ],
    book_cover_url: null,
    invite_token: null,
    pricing: "one_time",
    price_cents: 299,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["avatar", "art", "anime"],
    style_tags: ["anime", "comics"],
    like_count: 62,
    comment_count: 0,
    created_at: daysAgo(4),
    author: {
      id: "u2",
      username: "roninforge",
      display_name: "Ronin Forge",
      bio: null,
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: false,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "6",
    author_id: "u3",
    type: "story_segment",
    title: "The Hollow Gate — Complete Arc",
    description: "Full horror story arc with GM notes, handouts, and chapter breakdown.",
    plot_synopsis:
      "The complete Hollow Gate experience: seven chapters, sanity rules, printable handouts, and a GM guide for running the campaign.",
    content: "Chapter 1: Lantern at the Edge...",
    html_code: null,
    css_code: null,
    js_code: null,
    bbcode: null,
    preview_image_url: null,
    book_cover_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9b33?w=400&h=560&fit=crop",
    invite_token: null,
    pricing: "one_time",
    price_cents: 799,
    is_code_locked: false,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["horror", "story", "campaign"],
    style_tags: ["dark", "retro"],
    like_count: 112,
    comment_count: 0,
    created_at: daysAgo(2),
    author: {
      id: "u3",
      username: "leon_jezz",
      display_name: "Leon Jezz",
      bio: "Co-writing nightmares since 2019.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "7",
    author_id: "u1",
    type: "code_template",
    title: "Arcane Ledger — Premium Profile",
    description: "Animated inventory tabs, spell slots, and parchment styling.",
    plot_synopsis: null,
    content: null,
    html_code: "<div class='ledger'><h1>Spell Ledger</h1></div>",
    css_code: ".ledger { padding: 2rem; background: #f4e4bc; border: 3px double #8b4513; }",
    js_code: null,
    bbcode: null,
    preview_image_url:
      "https://images.unsplash.com/photo-1621357877523-abe879dcc084?w=400&h=560&fit=crop",
    book_cover_url: null,
    invite_token: null,
    pricing: "one_time",
    price_cents: 449,
    is_code_locked: true,
    moderation_status: "approved",
    is_ai_generated: false,
    tags: ["profile", "fantasy"],
    style_tags: ["retro", "fantasy"],
    like_count: 67,
    comment_count: 0,
    created_at: daysAgo(0),
    author: {
      id: "u1",
      username: "chaz_copper",
      display_name: "Chaz Copper",
      bio: "Building arcane UI for RPG personas.",
      avatar_url: null,
      banner_url: null,
      persona_mode: true,
      is_verified_creator: true,
      created_at: new Date().toISOString(),
    },
  },
];

export const EXPLORE_TAGS = [
  "fantasy", "sci-fi", "horror", "romance", "cyberpunk", "anime",
  "retro", "comics", "dark", "collab", "story", "character",
  "profile", "letters", "poem", "poetry", "rpg", "writing",
  "fiction", "essay", "lore", "mystical", "modern", "steampunk", "noir",
];

export const MOCK_FRIENDS = [
  { username: "chaz_copper", display_name: "Chaz Copper" },
  { username: "roninforge", display_name: "Ronin Forge" },
  { username: "leon_jezz", display_name: "Leon Jezz" },
];

export const MOCK_FORUMS: RpgForum[] = [
  {
    id: "f1",
    title: "The Hollow Gate",
    plot_synopsis:
      "A slow-burn horror campaign at the edge of a breathing forest gate — Victorian dread, lantern light, and secrets best left unopened.",
    book_cover_url: "https://images.unsplash.com/photo-1509248961154-86b1d4b1d2f4?w=300&h=420&fit=crop",
    creator_username: "leon_jezz",
    is_private: false,
    is_locked: false,
    locked_at: null,
    shop_post_id: null,
    shop_price_cents: null,
    category: "horror",
    tags: ["rpg", "campaign", "gothic", "play-by-post"],
    members: ["chaz_copper", "leon_jezz"],
    chapters: [
      {
        number: 1,
        title: "Part 1: Lantern at the Edge",
        meta: {
          era: "Victorian gothic",
          season: "Late autumn",
          location: "Blackfen Woods, eastern ridge",
          when: "Night of the red moon",
        },
        posts: [
          {
            id: "fp1",
            author_username: "leon_jezz",
            body: "The path narrows. Your lantern sputters. Roll Perception.",
            created_at: new Date().toISOString(),
          },
          {
            id: "fp2",
            author_username: "chaz_copper",
            body: "I steady the lantern and listen for footsteps that don't belong to us.",
            created_at: new Date().toISOString(),
          },
        ],
      },
    ],
    created_at: new Date().toISOString(),
  },
];
